#!/bin/bash

cd /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution
tmpDir=$(mktemp -d "$PWD"/tmp.XXXXXX)

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"


(
cd /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution

)


out0dc7ef16="${tmpDir}/out.$$" err0dc7ef16="${tmpDir}/err.$$"
mkfifo "$out0dc7ef16" "$err0dc7ef16"
trap 'rm "$out0dc7ef16" "$err0dc7ef16"' EXIT
touch '/home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/stdout' '/home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/stderr'
tee '/home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/stdout' < "$out0dc7ef16" &
tee '/home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/stderr' < "$err0dc7ef16" >&2 &
(
cd /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution


mkdir dir_collect
echo "Fastq files being moved from runfolder to Cromwell executions"
)  > "$out0dc7ef16" 2> "$err0dc7ef16"
echo $? > /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution
sync
# make the directory which will keep the matching files
mkdir /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /home/SBGS1/testfolder/*.fastq.gz /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa 2> /dev/null ) || ( ln /home/SBGS1/testfolder/*.fastq.gz /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa | grep -v cromwell_glob_control_file > /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/glob-dfb291c38e74a99167bb4612988fe0fa.list


)
mv /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/rc.tmp /home/SBGS1/cromwell-executions/main/0dc7ef16-7811-4827-908d-d447d6d8b7fd/call-find_files/execution/rc
